export const messageActions = {
  GET_MESSAGES : 'GET_MESSAGES',
  SET_MESSAGES: 'SET_MESSAGES',
  POST_MESSAGE_REQUESTED: 'POST_MESSAGE_REQUESTED',
  POST_MESSAGE_SUCCESS: 'POST_MESSAGE_SUCCESS',
  POST_MESSAGE_FAILED: 'POST_MESSAGE_FAILED',
}